Reorganize docs

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -56,7 +56,7 @@ jobs:
           [ "${{ inputs.version }}" == "${BUILD_VERSION}" ] || (>&2 echo "Version does not match value in build.properties"; exit -1)
           [ "${{ inputs.version }}" == "$(cat README.md | grep '<version>' | tr -d '<>/[:alpha:][:space:]')" ] || (>&2 echo "Version does not match value in the Maven instructions in README.md"; exit -1)
           [ "${{ inputs.version }}" == "$(cat README.md | grep "search.maven.org" | grep -oEi '[0-9]+\.[0-9]+(\.[0-9]+)?')" ] || (>&2 echo "Version does not match value in the Maven URL in README.md"; exit -1)
-          [ "${{ inputs.version }}" == "$(cat docs/news.md | grep "## " | head -n 1 | grep -oEi '[0-9]+\.[0-9]+(\.[0-9]+)?')" ] || (>&2 echo "Version does not match value in docs/news.md"; exit -1)
+          [ "${{ inputs.version }}" == "$(cat docs/releaseNotes.md | grep "## " | head -n 1 | grep -oEi '[0-9]+\.[0-9]+(\.[0-9]+)?')" ] || (>&2 echo "Version does not match value in docs/releaseNotes.md"; exit -1)
       - name: Build artifacts
         run: |
           ant package-binary
@@ -64,8 +64,8 @@ jobs:
           ant package-source
       - name: Generate release notes
         run: |
-          cat docs/news.md | awk '/## Version ${{ inputs.version }}/{flag=1; next} /##/{flag=0} flag' > dist/release_notes.md
-          [ "$(wc -l < dist/release_notes.md)" -gt 0 ] || (>&2 echo "Unable to read release notes from docs/news.md"; exit -1)
+          cat docs/releaseNotes.md | awk '/## Version ${{ inputs.version }}/{flag=1; next} /##/{flag=0} flag' > dist/releaseNotes.md
+          [ "$(wc -l < dist/releaseNotes.md)" -gt 0 ] || (>&2 echo "Unable to read release notes from docs/releaseNotes.md"; exit -1)
       - name: Build Maven artifacts
         if: ${{ inputs.publish_maven }}
         run: |
@@ -115,7 +115,7 @@ jobs:
       - name: Stage GitHub release
         if: ${{ inputs.publish_github }}
         run: |
-          gh release create "v${{ inputs.version }}" --draft --title "Version ${{ inputs.version }}" --notes-file dist/release_notes.md \
+          gh release create "v${{ inputs.version }}" --draft --title "Version ${{ inputs.version }}" --notes-file dist/releaseNotes.md \
               dist/MOEAFramework-${{ inputs.version }}.tar.gz \
               dist/MOEAFramework-${{ inputs.version }}-Demo.jar \
               dist/MOEAFramework-${{ inputs.version }}-Source.tar.gz
